query BreakdownByCategory($from : date, $to : date) {
        monthly_expenses_breakdown_by_category(where: {month: {_gte: $from, _lte: $to}}) {
            category_id
            month
            name
            sum
        }
    }
