query NumOfInvoiceItems($from : date, $to : date, $categoryId: Int, $shopId: Int) {
  invoice_items_aggregate(
    where: {
      invoice : {
        date: {_gte: $from, _lte: $to},
        shop_id: {_eq: $shopId }
      }
      category_id: { _eq: $categoryId }
    }) 
      {
        aggregate {
          count
        }
  }
}