query NumOfInvoices($from : date, $to : date, $categoryId: Int, $shopId: Int) {
  invoices_aggregate(where: {
      date: {_gte: $from, _lte: $to}, 
      shop_id: {_eq: $shopId}
      items: {
        category_id: { _eq: $categoryId }
      }
    }) {
    aggregate {
      count
    }
  }
}